   	<div class="categ_wrapper">
        <ul class="categories">
            <li><a>Appliances</a></li>
            <li><a>Arts</a></li>
            <li><a>Beauty</a></li>
            <li><a>Books</a></li> 
            <li><a>CD/DVD</a></li>
            <li><a>Clothings</a></li>
            <li><a>Computers</a></li>
            <li><a>Electronics</a></li>
            <li><a>Kitchen</a></li>
            <li><a>Handphones</a></li>
            <li><a>Jewelries</a></li>
            <li><a>NBS</a></li>
            <li><a>SCE</a></li>
            <li><a>SBS</a></li>
            <li><a>SPMS</a></li>
            <li><a>MAE</a></li>
            <li><a>MSE</a></li>
            <li><a>Handphones</a></li>
            <li><a>Jewelries</a></li>
            <li><a>NBS</a></li>
            <li><a>SCE</a></li>
            <li><a>SBS</a></li>
            <li><a>SPMS</a></li>
            <li><a>MAE</a></li>
            <li><a>MSE</a></li>
            <li><a>NBS</a></li>
            <li><a>SCE</a></li>
            <li><a>SBS</a></li>
            <li><a>SPMS</a></li>
            <li><a>MAE</a></li>
            <li><a>MSE</a></li>
            <li><a>NBS</a></li>
            <li><a>SCE</a></li>
            <li><a>SBS</a></li>
            <li><a>SPMS</a></li>
            <li><a>MAE</a></li>
            <li><a>MSE</a></li>
    	</ul>
    </div>
