   	<div class="categ_wrapper">
        <ul class="categories">
			<?php
				if(isset($tags)&&$tags) {
					echo "<li><a><strong>Categories: </strong></a></li>";
					foreach($tags as $val) if($val['special']=='no') echo "<li><a href=\"".site_url()."/item/listing/tag/".$val['tagID']."\">".ucfirst($val['tagname'])."</a></li>";
					echo "<li><a><strong>Special users: </strong></a></li>";
					foreach($tags as $val) if($val['special']=='yes') echo "<li><a href=\"".site_url()."/item/listing/tag/".$val['tagID']."\">".ucfirst($val['tagname'])."</a></li>";
				} 
			?>
    	</ul>
		<!--
		<ul class="categories" style="width: 1858px; ">
			<li><a><strong>Categories: </strong></a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/1">Appliances</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/2">Arts</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/3">Beauty accessories</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/4">Books</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/5">CD/DVD</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/6">Clothings</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/7">Computers</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/9">Electronic accessories</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/8">Electronics</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/10">Handphones</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/11">Jewelries</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/12">Kitchen utensils</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/14">Religion</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/16">Shoes</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/17">Sports</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/18">Stationaries</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/19">Watches</a></li><li><a><strong>Special users: </strong></a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/21">ABC</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/22">ADM</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/32">CAC</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/23">CEE</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/24">EEE</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/25">HSS</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/26">MAE</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/27">MSE</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/13">NBS</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/31">NIE</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/20">SBS</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/28">SCBE</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/15">SCE</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/29">SCI</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/30">SPMS</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/33">Sports Club</a></li><li><a href="http://localhost/umall/index.php/item/listing/tag/34">WSC</a></li>    	</ul>
		-->
    </div>
